### ISSUE TITLE
Cannot Download the songs

### ISSUE THREAD

**Issue by arushk1** [flyingrub/scdl#85] opened 2015-09-04 13:03 UTC
Here is the full output: 

Soundcloud Downloader

Found an user profile
Traceback (most recent call last):
  File "/usr/lib/python3.4/urllib/request.py", line 1232, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.4/http/client.py", line 1065, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.4/http/client.py", line 1103, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.4/http/client.py", line 1061, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.4/http/client.py", line 906, in _send_output
    self.send(msg)
  File "/usr/lib/python3.4/http/client.py", line 841, in send
    self.connect()
  File "/usr/lib/python3.4/http/client.py", line 1197, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python3.4/socket.py", line 491, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.4/socket.py", line 530, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/scdl", line 9, in <module>
    load_entry_point('scdl==v1.3.2', 'console_scripts', 'scdl')()
  File "/usr/local/lib/python3.4/dist-packages/scdl/scdl.py", line 115, in main
    parse_url(arguments["-l"])
  File "/usr/local/lib/python3.4/dist-packages/scdl/scdl.py", line 190, in parse_url
    download_all_user_tracks(item)
  File "/usr/local/lib/python3.4/dist-packages/scdl/scdl.py", line 224, in download_all_user_tracks
    response = urllib.request.urlopen(url)
  File "/usr/lib/python3.4/urllib/request.py", line 153, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 455, in open
    response = self._open(req, data)
  File "/usr/lib/python3.4/urllib/request.py", line 473, in _open
    '_open', req)
  File "/usr/lib/python3.4/urllib/request.py", line 433, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 1273, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.4/urllib/request.py", line 1235, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>

**Comment by Spotlight0xff** [comment] 2015-09-04 13:21
Does this happen with every song? 
Please provide a commandline so we can reproduce.

**Comment by scumola** [comment] 2015-09-21 23:12
I'm getting the same error:

/opt/python3.3/bin/scdl --onlymp3 -a -c -l http://soundcloud.com/pow-746801448

**Comment by Spotlight0xff** [comment] 2015-09-22 09:55
I can download the track just fine (But it does get an error while trying to set the tags).
It looks more like a firewall issue... or are you behind a proxy/vpn which may interfere?

**Comment by scumola** [comment] 2015-09-22 15:25
No, no firewall or VPN.  Full output here: http://pastebin.com/b424Nz6L

**Comment by scumola** [comment] 2015-09-22 15:25
I can download the uploads and the favorites, but the -a switch fails for me.

**Comment by flyingrub** [comment] 2015-09-22 15:59
> I'm using python 3.3.5 and it all seemed to build/install correctly.
Could you try with a more recent version ?

**Comment by flyingrub** [comment] 2015-09-22 16:07
https://github.com/flyingrub/scdl/issues/87 could be a fix

**Comment by ahhdem** [comment] 2015-10-25 21:26
I am also experiencing this issue - python 3.5 installed via brew on osx 10.9.5:

```
studio:Music adam$ scdl -a -l https://soundcloud.com/magnafide/
Soundcloud Downloader

Found an user profile
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 1240, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1083, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1128, in _send_request
    self.endheaders(body)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1079, in endheaders
    self._send_output(message_body)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 911, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 854, in send
    self.connect()
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1229, in connect
    super().connect()
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 826, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py", line 689, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py", line 728, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/scdl", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/scdl/scdl.py", line 115, in main
    parse_url(arguments["-l"])
  File "/usr/local/lib/python3.5/site-packages/scdl/scdl.py", line 190, in parse_url
    download_all_user_tracks(item)
  File "/usr/local/lib/python3.5/site-packages/scdl/scdl.py", line 224, in download_all_user_tracks
    response = urllib.request.urlopen(url)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 162, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 465, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 483, in _open
    '_open', req)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 443, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 1283, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 1242, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 8] nodename nor servname provided, or not known>
studio:Music adam$ scdl -a -l https://soundcloud.com/magnafide/speaking-in-tongues-shadows-dubsky-magnafide-rmx
Soundcloud Downloader

Found a track
Downloading Speaking in Tongues - 'Shadows' (Dubsky & Magnafide Rmx)
100% [..........................................................................] 2999274 / 2999274
Settings tags...

Speaking in Tongues - 'Shadows' (Dubsky & Magnafide Rmx).mp3 Downloaded.

studio:Music adam$ head $(which scdl)
#!/usr/local/opt/python3/bin/python3.5

# -*- coding: utf-8 -*-
import re
import sys

from scdl.scdl import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
studio:Music adam$
```

**Comment by flyingrub** [comment] 2015-10-25 22:13
thanks for the debug.
feel free to pull request ;)

**Comment by ahhdem** [comment] 2015-10-25 22:17
Looks fixed in master.. seems you fixed it here:  https://github.com/ahhdem/scdl/commit/3f7fc89f1fcb27f020399eab996b03c0ae005ab9

but in the pip3 installed version, it's still using the sndcdn host :(

**Comment by flyingrub** [comment] 2015-10-25 22:31
https://pypi.python.org/pypi/scdl/1.4.0b1, it's your pip cache. Try to install it from source :)

**Comment by dustinmiller** [comment] 2015-11-05 17:45
pip3 install scdl==1.4.0b1

Works for me now :+1:

**Closed** 2015-11-15 17:27 UTC

**Comment by Suave101** [comment] 2021-04-04 19:57
If it doesn't work try turning off your firewall and or VPN.
