### ISSUE TITLE
[Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by xnrx** [flyingrub/scdl#108] opened 2016-02-07 04:10 UTC
```
[music/like] scdl -l https://soundcloud.com/rst-x0 -f
Soundcloud Downloader

Found a user profile
Retrieving the favorites of user Rst x0...
Retrieved 116 favorites
Favorite n°1 of 116
Downloading Tilendria Falls
Downloading the orginal file.
  0% [                                                                          ]   24576 / 7681990[Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/scdl-1.4.1-py3.5.egg/scdl/scdl.py", line 263, in download_all_of_user
    download_function(item)
  File "/usr/lib/python3.5/site-packages/scdl-1.4.1-py3.5.egg/scdl/scdl.py", line 379, in download_track
    wget.download(url, filename)
  File "/usr/lib/python3.5/site-packages/wget.py", line 526, in download
    (tmpfile, headers) = ulib.urlretrieve(binurl, tmpfile, callback)
  File "/usr/lib/python3.5/urllib/request.py", line 216, in urlretrieve
    block = fp.read(bs)
  File "/usr/lib/python3.5/http/client.py", line 433, in read
    n = self.readinto(b)
  File "/usr/lib/python3.5/http/client.py", line 473, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Favorite n°2 of 116
Downloading KOAN Sound & Asa - This Time Around ft. Koo
```

This happens all the time for specific songs. 

For more example:

```
[music/like] scdl -l https://soundcloud.com/sacredaus/the-meaning-of-life
Soundcloud Downloader

Found a track
Downloading The Meaning Of Life
Downloading the orginal file.
  0% [                                                                        ]    24576 / 10006463Traceback (most recent call last):
  File "/usr/bin/scdl", line 9, in <module>
    load_entry_point('scdl==1.4.1', 'console_scripts', 'scdl')()
  File "/usr/lib/python3.5/site-packages/scdl-1.4.1-py3.5.egg/scdl/scdl.py", line 114, in main
  File "/usr/lib/python3.5/site-packages/scdl-1.4.1-py3.5.egg/scdl/scdl.py", line 177, in parse_url
  File "/usr/lib/python3.5/site-packages/scdl-1.4.1-py3.5.egg/scdl/scdl.py", line 379, in download_track
  File "/usr/lib/python3.5/site-packages/wget.py", line 526, in download
    (tmpfile, headers) = ulib.urlretrieve(binurl, tmpfile, callback)
  File "/usr/lib/python3.5/urllib/request.py", line 216, in urlretrieve
    block = fp.read(bs)
  File "/usr/lib/python3.5/http/client.py", line 433, in read
    n = self.readinto(b)
  File "/usr/lib/python3.5/http/client.py", line 473, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
```

Songs downloading only for 24K size.

**Comment by xnrx** [comment] 2016-02-07 04:14
I also tried to use my unique client_id, but this didnt help and tested it on two systems ( Ubuntu 16.04 and Arch).

**Comment by FloThinksPi** [comment] 2016-02-07 17:38
Cannot reproduce : 

```
scdl -l https://soundcloud.com/sacredaus/the-meaning-of-life
Soundcloud Downloader

Found a track
Downloading The Meaning Of Life
Downloading the orginal file.
100% [....................................................] 10006463 / 10006463
Settings tags...
```

Can you test again weather its working for you now ?

**Comment by xnrx** [comment] 2016-02-07 17:46
```
[music/like] scdl -l https://soundcloud.com/sacredaus/the-meaning-of-life
Soundcloud Downloader

Found a track
Downloading The Meaning Of Life
Downloading the orginal file.
  0% [                                                                        ]    24576 / 10006463Traceback (most recent call last):
  File "/usr/bin/scdl", line 9, in <module>
    load_entry_point('scdl==1.4.1', 'console_scripts', 'scdl')()
  File "/usr/lib/python3.5/site-packages/scdl-1.4.1-py3.5.egg/scdl/scdl.py", line 114, in main
  File "/usr/lib/python3.5/site-packages/scdl-1.4.1-py3.5.egg/scdl/scdl.py", line 177, in parse_url
  File "/usr/lib/python3.5/site-packages/scdl-1.4.1-py3.5.egg/scdl/scdl.py", line 379, in download_track
  File "/usr/lib/python3.5/site-packages/wget.py", line 526, in download
    (tmpfile, headers) = ulib.urlretrieve(binurl, tmpfile, callback)
  File "/usr/lib/python3.5/urllib/request.py", line 216, in urlretrieve
    block = fp.read(bs)
  File "/usr/lib/python3.5/http/client.py", line 433, in read
    n = self.readinto(b)
  File "/usr/lib/python3.5/http/client.py", line 473, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
```
Still not work, this happens for a whole week or more.

**Comment by FloThinksPi** [comment] 2016-02-07 18:52
can you post scdl -l https://soundcloud.com/sacredaus/the-meaning-of-life --debug

**Comment by xnrx** [comment] 2016-02-07 18:54
```
[music/like] scdl -l https://soundcloud.com/sacredaus/the-meaning-of-life --debug


Soundcloud Downloader
{'--addtofile': False,
 '--debug': True,
 '--error': False,
 '--help': False,
 '--hide-progress': False,
 '--hidewarnings': False,
 '--onlymp3': False,
 '--path': None,
 '--version': False,
 '-a': False,
 '-c': False,
 '-f': False,
 '-l': 'https://soundcloud.com/sacredaus/the-meaning-of-life',
 '-o': None,
 '-p': False,
 '-s': False,
 '-t': False,
 'me': False}
Downloading to /storage/data/music/like...

Found a track
Downloading The Meaning Of Life
Downloading the orginal file.
  0% [                                                                        ]    24576 / 10006463Traceback (most recent call last):
  File "/usr/bin/scdl", line 9, in <module>
    load_entry_point('scdl==1.4.1', 'console_scripts', 'scdl')()
  File "/usr/lib/python3.5/site-packages/scdl-1.4.1-py3.5.egg/scdl/scdl.py", line 114, in main
  File "/usr/lib/python3.5/site-packages/scdl-1.4.1-py3.5.egg/scdl/scdl.py", line 177, in parse_url
  File "/usr/lib/python3.5/site-packages/scdl-1.4.1-py3.5.egg/scdl/scdl.py", line 379, in download_track
  File "/usr/lib/python3.5/site-packages/wget.py", line 526, in download
    (tmpfile, headers) = ulib.urlretrieve(binurl, tmpfile, callback)
  File "/usr/lib/python3.5/urllib/request.py", line 216, in urlretrieve
    block = fp.read(bs)
  File "/usr/lib/python3.5/http/client.py", line 433, in read
    n = self.readinto(b)
  File "/usr/lib/python3.5/http/client.py", line 473, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
```

**Comment by flyingrub** [comment] 2016-02-07 22:46
i already had this error a few times. I think it comes from the soundcloud server randomly.

**Comment by flyingrub** [comment] 2016-02-08 01:19
it should be fixed with the latest commit.

**Comment by xnrx** [comment] 2016-02-08 01:24
```
[music/like] scdl -l https://soundcloud.com/sacredaus/the-meaning-of-life
Soundcloud Downloader

Found a track
Downloading The Meaning Of Life
Downloading the orginal file.
Traceback (most recent call last):
  File "/usr/bin/scdl", line 9, in <module>
    load_entry_point('scdl==1.4.1', 'console_scripts', 'scdl')()
  File "/usr/lib/python3.5/site-packages/scdl-1.4.1-py3.5.egg/scdl/scdl.py", line 114, in main
  File "/usr/lib/python3.5/site-packages/scdl-1.4.1-py3.5.egg/scdl/scdl.py", line 179, in parse_url
  File "/usr/lib/python3.5/site-packages/scdl-1.4.1-py3.5.egg/scdl/scdl.py", line 361, in download_track
NameError: name 're' is not defined
```

**Comment by xnrx** [comment] 2016-02-08 02:06
After    [f54ab00bff069205ac04183dc35f4f9e8d689b59](https://github.com/flyingrub/scdl/commit/f54ab00bff069205ac04183dc35f4f9e8d689b59)
```
[music/like] scdl -l https://soundcloud.com/sacredaus/the-meaning-of-life
Soundcloud Downloader

Found a track
Downloading The Meaning Of Life
Downloading the orginal file.
[################################] 29/9772 - 00:00:00
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 226, in _error_catcher
    yield
  File "/usr/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 301, in read
    data = self._fp.read(amt)
  File "/usr/lib/python3.5/http/client.py", line 433, in read
    n = self.readinto(b)
  File "/usr/lib/python3.5/http/client.py", line 473, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/requests/models.py", line 660, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 344, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 311, in read
    flush_decoder = True
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 244, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
requests.packages.urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/scdl", line 9, in <module>
    load_entry_point('scdl==1.4.1', 'console_scripts', 'scdl')()
  File "/usr/lib/python3.5/site-packages/scdl-1.4.1-py3.5.egg/scdl/scdl.py", line 115, in main
  File "/usr/lib/python3.5/site-packages/scdl-1.4.1-py3.5.egg/scdl/scdl.py", line 180, in parse_url
  File "/usr/lib/python3.5/site-packages/scdl-1.4.1-py3.5.egg/scdl/scdl.py", line 383, in download_track
  File "/usr/lib/python3.5/site-packages/clint-0.5.1-py3.5.egg/clint/textui/progress.py", line 115, in bar
  File "/usr/lib/python3.5/site-packages/requests/models.py", line 663, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))
```

**Comment by flyingrub** [comment] 2016-02-08 12:43
try the latest commit too it works well here.

**Closed by flyingrub** 2016-02-08 12:43 UTC
Labels: bug
