### ISSUE TITLE
Error trying to set the tags...

### ISSUE THREAD

**Issue by briancurtis4** [flyingrub/scdl#176] opened 2017-03-13 00:02 UTC
Scdl seemed to be working several days ago, but now on my current installation and on any new installations I get the error "Error trying to set the tags..." when trying to grab any song.

**Comment by thehamzan6** [comment] 2017-03-13 05:33
Can confirm that this is happening.

**Comment by terryttsai** [comment] 2017-03-13 06:33
I am also getting this error.

**Comment by flyingrub** [comment] 2017-03-13 09:12
I can confirm this bug, but it's a duplicate of https://github.com/flyingrub/scdl/issues/148.
Closing this one.

**Closed by flyingrub** 2017-03-13 09:12 UTC
