### ISSUE TITLE
Download playlist doesn't download full playlist

### ISSUE THREAD

**Issue by KingJojo** [flyingrub/scdl#152] opened 2016-07-20 17:30 UTC
Downloading this playlist: https://soundcloud.com/user-788157240/sets/random

Not all songs downloaded when trying to download this playlist.

**Comment by robski888** [comment] 2016-07-20 17:52
i think it has something to do with the charmap

UnicodeEncodeError: 'charmap' codec can't encode character '\u0393' in position 33: character maps to <undefined>

do the download stop on error or continue without one?

**Comment by KingJojo** [comment] 2016-07-20 18:12
it continues

**Comment by flyingrub** [comment] 2016-09-27 17:31
could you provide the output of the terminal ?

**Comment by tamblc** [comment] 2016-09-27 20:19
When I reproduced the issue, it simply did not download all the songs, it didn't actually error out.

**Comment by flyingrub** [comment] 2016-09-27 21:23
Without any log, i wont be able to fix this issue... Could retry to run the command ?

**Comment by aspel** [comment] 2017-01-26 21:30
The problem is not in your program. SoundCloud does not return all data.
For example: https://api.soundcloud.com/resolve?url=https://soundcloud.com/aspel-lip/sets/car-mus&client_id=95a4c0ef214f2a4a0852142807b54b35
"track_count":138,
But server return to me only 88 tracks.

**Comment by flyingrub** [comment] 2017-01-27 15:22
I think we can close this as`wontfix`

**Closed by flyingrub** 2017-01-27 15:22 UTC
Labels: bug, cannot reproduce
