### ISSUE TITLE
HTTPError: 403 Client Error: Forbidden for url:

### ISSUE THREAD

**Issue by bkinsey808** [flyingrub/scdl#109] opened 2016-02-07 06:12 UTC
scdl -l "https://soundcloud.com/mettaben" -f

Found an user profile
Retrieving the favorites of user mettaben...
Traceback (most recent call last):
  File "/usr/local/bin/scdl", line 9, in <module>
    load_entry_point('scdl==1.4.1', 'console_scripts', 'scdl')()
  File "/usr/local/lib/python3.4/dist-packages/scdl/scdl.py", line 114, in main
    parse_url(arguments['-l'])
  File "/usr/local/lib/python3.4/dist-packages/scdl/scdl.py", line 185, in parse_url
    download_all_of_user(item, 'favorite', download_track)
  File "/usr/local/lib/python3.4/dist-packages/scdl/scdl.py", line 255, in download_all_of_user
    items = client.get_all('/users/{0.id}/{1}s'.format(user, name), offset=offset)
  File "/usr/local/lib/python3.4/dist-packages/scdl/soundcloud.py", line 14, in get_all
    resources.extend(self.get(url, offset=offset, limit=limit, **kwargs))
  File "/home/bkinsey/.local/lib/python3.4/site-packages/soundcloud/client.py", line 133, in _request
    return wrapped_resource(make_request(method, url, kwargs))
  File "/home/bkinsey/.local/lib/python3.4/site-packages/soundcloud/request.py", line 148, in make_request
    result.raise_for_status()
  File "/home/bkinsey/.local/lib/python3.4/site-packages/requests/models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.soundcloud.com/users/3677232/favorites?limit=200&client_id=95a4c0ef214f2a4a0852142807b54b35&offset=399

**Comment by FloThinksPi** [comment] 2016-02-07 17:34
When clicking the url which is in your Traceback, it is still forbidden. 

Howerver when i run scdl -l "https://soundcloud.com/mettaben" -f , it downloads the favorites ( i abordet at 50/1300)  so i cannot reproduce that behaviour. Did you do something else ? does it still happen to you?

**Comment by flyingrub** [comment] 2016-02-08 01:19
should be fixed with latest commit

**Comment by bkinsey808** [comment] 2016-02-08 08:46
Do I get the latest version if I `pip3 install scdl` ? Because my version still says 1.4.1 and I'm getting the same problem.

**Comment by xnrx** [comment] 2016-02-08 08:53
Install it on source. Clone this repo and write `sudo python3 setyp.py install`.

**Comment by bkinsey808** [comment] 2016-02-08 09:03
Ok, cloned latest repo. Now I get a different error. I've clipped the last two entries.

```
'Resource' object is not subscriptable
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/scdl-1.4.1-py3.4.egg/scdl/scdl.py", line 265, in download_all_of_user
    download_function(item)
  File "/usr/local/lib/python3.4/dist-packages/scdl-1.4.1-py3.4.egg/scdl/scdl.py", line 341, in download_track
    if track['streamable']:
TypeError: 'Resource' object is not subscriptable
Favorite n°1468 of 1468
'Resource' object is not subscriptable
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/scdl-1.4.1-py3.4.egg/scdl/scdl.py", line 265, in download_all_of_user
    download_function(item)
  File "/usr/local/lib/python3.4/dist-packages/scdl-1.4.1-py3.4.egg/scdl/scdl.py", line 341, in download_track
    if track['streamable']:
TypeError: 'Resource' object is not subscriptable
Downloaded all 1468 favorites of user mettaben!
```

**Comment by flyingrub** [comment] 2016-02-08 12:42
weird it works well here... This issue is fixed. Reopen another one if it persist.

**Closed by flyingrub** 2016-02-08 12:42 UTC
Labels: bug
