### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by Aggelos010** [flyingrub/scdl#91] opened 2015-10-13 11:17 UTC
Hi,

For some silly I decided to uninstall scdl(probably in an attempt to update it) and now I can't install it again...

Error:
Downloading/unpacking scdl
  Cannot fetch index base URL https://pypi.python.org/simple/
  Could not find any downloads that satisfy the requirement scdl
Cleaning up...
No distributions at all found for scdl
Storing debug log for failure in /home/maahloth/.pip/pip.log

Command:
sudo pip3 --proxy http://user:pword@proxy:80 install scdl

Any ideas?

**Comment by flyingrub** [comment] 2015-10-13 13:58
it probably come from your proxy... It works well here.

**Comment by flyingrub** [comment] 2015-10-18 11:05
as i cannot reproduce i close this issue. if you have more information feel free to reopen it.

**Closed by flyingrub** 2015-10-18 11:05 UTC

**Comment by Aggelos010** [comment] 2015-10-19 07:40
It was the proxy, managed to install it successfully on open network
