### ISSUE TITLE
Tracks by the same user are always skipped when downloading my Liked Tracks

### ISSUE THREAD

**Issue by winterflags** [flyingrub/scdl#185] opened 2017-04-15 20:27 UTC
For some reason that I can't figure out, scdl skips both of these tracks (in sequence), but NOT tracks immediately before and after these two, in my like list:

https://soundcloud.com/toddterje/jungelknugen-four-tet-remix
https://soundcloud.com/toddterje/jungelknugen-prins-thomas-remix

I am running: `scdl -l https://soundcloud.com/myuser -f -c --addtofile --path /Users/me/mypath`

The tracks above are not listed in Terminal. Instead, the tracks before and after are listed:

> Likes n°60 of 3284
Downloading B1. Heat Sequence - Minimal Afrika [UNTO 05]
B1. Heat Sequence - Minimal Afrika [UNTO 05] already Downloaded
Likes n°61 of 3284
Downloading PREMIERE: Robert D - Un Ni Yo [9300 Records]

The two tracks should've actually been between n°60 and n°61.

I have run the script multiple times over the last few days, including after adding more tracks to my liked list. The two tracks have never been listed, because otherwise I would have them on the disk.

Both tracks are uploaded by the same user to Soundcloud.

**Comment by flyingrub** [comment] 2017-04-20 15:53
I added them to a playlist and the download went fine here. 😕
Could you give me the exact command you tried when you had this error ?

**Comment by winterflags** [comment] 2017-04-21 13:21
Tried it now again, these two tracks are still problematic in the same way.

The command I ran is the same as in the OP, with Python 3.5.0:
`scdl -l https://soundcloud.com/myuser -f -c --addtofile --path /Users/me/mypath`

**Comment by flyingrub** [comment] 2017-04-21 18:44
It would be great to have your username too. :)

**Comment by winterflags** [comment] 2017-04-24 09:48
User [here](https://soundcloud.com/niklasnordstrom)

**Comment by flyingrub** [comment] 2017-04-24 10:30
Those tracks doesn't appear in the favorite API.
I tried to like it and download my like it didn't worked too... 
It's related to our client_id.

**Comment by flyingrub** [comment] 2017-04-24 13:14
Those tracks doesn't appear in the favorite API.
I tried to like it and download my like it didn't worked too... 
It's related to our client_id.

**Comment by flyingrub** [comment] 2017-09-19 13:37
duplicate of https://github.com/flyingrub/scdl/issues/185

**Closed by flyingrub** 2017-09-19 13:37 UTC
Labels: bug
